### PR TITLE
feat: added performance metric grpahs config for nvidia nim

### PR DESCRIPTION
**Pull request by TomerFi**
## Description

Added metrics graphs configuration for NVIDIA NIM runtimes, including logic for identifying said runtimes:
| Graph | Query |
| ------ | ------ |
| Requests per 5 minutes | Number of successful incoming requests |
|  | Number of failed incoming requests |
| Average response time (ms) | Average inference latency **(not included)** |
|  | Average e2e latency |
| CPU utilization %	| CPU usage |
| Memory utilization % | Memory usage |

Currently, NIM runtimes do not report inference latency (see [here](https://docs.nvidia.com/nim/large-language-models/latest/observability.html)). Hence, the _Average inference latency_ query is **NOT** included in this PR.

**This PR includes**:
- Modifying the Template for NIM's ServingRuntimes:
  - Adding runtime metadata annotation for identification.
  - Adding runtime spec annotations for ISTIO Prometheus metrics merge.
- Adding metrics JSON object encapsulating NVIDIA NIM queries.
- Modified metrics JSON selection process to return the new NVIDIA NIM object for runtimes annotated accordingly.

Jira: [NVPE-30](https://issues.redhat.com/browse/NVPE-30).

## How Has This Been Tested?

This work was tested against an OpenShift cluster (dev04):
- I deployed NIM runtime.
- I executed a couple of requests against the runtime.
- I connected to the ISTIO sidecar and verified the metrics merge.
- I opened the related graphs page and verified them (see attached snapshot).

image

> [!NOTE]  
> Since graphs are currently turned off for NIM runtimes, after enabling locally on my computer, the snapshot was taken from a frontend running on my local against the remote cluster. Jira for enabling: [NVPE-18](https://issues.redhat.com/browse/NVPE-18)

> [!NOTE]
> Building and testing the queries required enabling monitoring for user-defined projects (see [here](https://docs.openshift.com/container-platform/4.17/observability/monitoring/enabling-monitoring-for-user-defined-projects.html)), to make the runtime metrics available from OpenShift Metrics dashboard.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by spolti** [comment]
changes looks good to me, just one question, should we align this with the dashboard team?

**Review by spolti — APPROVED** [review]

**Comment by TomerFi** [comment]
> changes looks good to me, just one question, should we align this with the dashboard team?

@spolti—We're working with them. Currently, nim metrics are disabled in the dashboard. We have a [Jira]([NVPE-18](https://issues.redhat.com/browse/NVPE-18)) in place to eventually enable them back.

**Comment by spolti** [comment]
Okay, thanks.

**Review by israel-hdez — COMMENTED** [review]
I have a small suggestion. But otherwise it is OK.

If you think that the current code is fine, let me know, and I will approve.

**Comment by TomerFi** [comment]
> I have a small suggestion. But otherwise it is OK.
> 
> If you think that the current code is fine, let me know, and I will approve.

Good idea. I accepted the change suggestion.

**Review by israel-hdez — APPROVED** [review]
/lgtm

**Pull request merged**
