### PR TITLE
Prepare for ODH release and update params env to 0.11.1.3

### PR DESCRIPTION
**Pull request by heyselbi**
Please note that the target branch is release-0.12.0 although the tag is 0.11.1.3 per @israel-hdez's request. This is so we can match with the rest of the stack semantics for this ODH release.

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
LGTM but @israel-hdez please confirm:

> Please note that the target branch is release-0.12.0 although the tag is 0.11.1.3 per @israel-hdez's request. This is so we can match with the rest of the stack semantics for this ODH release.

**Comment by israel-hdez** [comment]
> LGTM but @israel-hdez please confirm:
> 
> > Please note that the target branch is release-0.12.0 although the tag is 0.11.1.3 per @israel-hdez's request. This is so we can match with the rest of the stack semantics for this ODH release.

This is more like a @Jooho request than mine. But yes, this is what we want to do.

/lgtm

**Pull request merged**
