### PR TITLE
Cherrypick PRs for Kserve Dashboard Metrics

### PR DESCRIPTION
**Pull request by VedantMahabaleshwarkar**
## Description

Cherrypicking #240 and #245 
also for some reason `/controllers/comparators/configmap_comparator.go` and `/controllers/resources/configmap.go` were missing after the cherry-picks (probably due to the revert on this branch earlier for the metrics PR) so I added them back from the original PR 

## How Has This Been Tested?

Confirmed units pass, no other testing needed as it is a cherrypick 

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
You are cherry picking the merge commits. Is that intended?

**Review by mwaykole — APPROVED** [review]

**Review by mwaykole — COMMENTED** [review]
/lgtm

**Comment by terrytangyuan** [comment]
Got it. No problem

**Pull request merged**
