### PR TITLE
[0.11.0-alpha] Add anti-affinity rules to manager pod

### PR DESCRIPTION
**Pull request by israel-hdez**
Cherry-pick of #51 to `release-v0.11.0-alpha` branch.

### CODE REVIEW

**Comment by Jooho** [comment]
@israel-hdez this looks good to me. Could you please try to fix openshift-ci for fvt?

**Comment by israel-hdez** [comment]
> Could you please try to fix openshift-ci for fvt?

@Jooho It is now passing.

**Review by Jooho — APPROVED** [review]
/lgtm

**Pull request merged**
