### PR TITLE
Upgrade to go 1.18

### PR DESCRIPTION
**Pull request by VedantMahabaleshwarkar**
## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by zdtsw** [comment]
no plan to change https://github.com/opendatahub-io/odh-model-controller/blob/main/go.mod#L3 ?

**Comment by zdtsw** [comment]
> @zdtsw updated

not sure if should update `go.sum` or just keep it as-is?  see a lot can be cleaned up

**Comment by Jooho** [comment]
@VedantMahabaleshwarkar please read the template description and update it properly.
It does not have any description and no tick on anything. 
~~~
 The commits are squashed in a cohesive manner and have meaningful messages.
 Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
 The developer has manually tested the changes and verified that the changes work
~~~
Moreover, please squash the 2 commits into 1 and add signature for your commit. 

Did you test it on your local first? As @zdtsw mentioned, I think the go.sum should be updated as well. the file will be updated when you try to build it on your local.

**Comment by Jooho** [comment]
@VedantMahabaleshwarkar it's been 1 month. Do you still need this ?

**Comment by israel-hdez** [comment]
@VedantMahabaleshwarkar @Jooho Can we, please, update this PR targeting go1.20?

Versions 1.18 and earlier are already EoL. Version 1.19 is soon going EoL. So, right now, it is better to move to go1.20.

**Comment by VedantMahabaleshwarkar** [comment]
I think this particular PR was made for a build issue but it was not needed for the fix. I think it is best to close this one out and make a fresh issue and pr for the go 1.20 upgrade

**Pull request closed without merging**
